# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"3\n\x10LoginUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"B\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\";\n\x0f\x41uthUserReponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\x12\r\n\x05token\x18\x02 \x01(\t\"\x11\n\x0fGetUsersRequest\".\n\x10GetUsersResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User\"\x10\n\x0eGetUserRequest\".\n\x11UpdateUserRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"/\n\x12UpdateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"\x1f\n\x11\x44\x65IeteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x12\x44\x65leteUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User2\x87\x03\n\x05Users\x12>\n\tLoginUser\x12\x17.users.LoginUserRequest\x1a\x16.users.AuthUserReponse\"\x00\x12\x33\n\x0bGetUserById\x12\x15.users.GetUserRequest\x1a\x0b.users.User\"\x00\x12=\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x17.users.GetUsersResponse\"\x00\x12@\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x16.users.AuthUserReponse\"\x00\x12\x43\n\nUpdateUser\x12\x18.users.UpdateUserRequest\x1a\x19.users.UpdateUserResponse\"\x00\x12\x43\n\nDeleteUser\x12\x18.users.DeIeteUserRequest\x1a\x19.users.DeleteUserResponse\"\x00\x42&\n\x0fio.server.usersB\nUsersProtoP\x01\xa2\x02\x04USRSb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017io.server.usersB\nUsersProtoP\001\242\002\004USRS'
  _globals['_USER']._serialized_start=22
  _globals['_USER']._serialized_end=69
  _globals['_LOGINUSERREQUEST']._serialized_start=71
  _globals['_LOGINUSERREQUEST']._serialized_end=122
  _globals['_CREATEUSERREQUEST']._serialized_start=124
  _globals['_CREATEUSERREQUEST']._serialized_end=190
  _globals['_AUTHUSERREPONSE']._serialized_start=192
  _globals['_AUTHUSERREPONSE']._serialized_end=251
  _globals['_GETUSERSREQUEST']._serialized_start=253
  _globals['_GETUSERSREQUEST']._serialized_end=270
  _globals['_GETUSERSRESPONSE']._serialized_start=272
  _globals['_GETUSERSRESPONSE']._serialized_end=318
  _globals['_GETUSERREQUEST']._serialized_start=320
  _globals['_GETUSERREQUEST']._serialized_end=336
  _globals['_UPDATEUSERREQUEST']._serialized_start=338
  _globals['_UPDATEUSERREQUEST']._serialized_end=384
  _globals['_UPDATEUSERRESPONSE']._serialized_start=386
  _globals['_UPDATEUSERRESPONSE']._serialized_end=433
  _globals['_DEIETEUSERREQUEST']._serialized_start=435
  _globals['_DEIETEUSERREQUEST']._serialized_end=466
  _globals['_DELETEUSERRESPONSE']._serialized_start=468
  _globals['_DELETEUSERRESPONSE']._serialized_end=515
  _globals['_USERS']._serialized_start=518
  _globals['_USERS']._serialized_end=909
# @@protoc_insertion_point(module_scope)
