// Copyright 2015 gRPC authors.
// Use CMD below to generate the Python code from this proto file:
// python -m grpc_tools.protoc -I./protos --python_out=. --pyi_out=. --grpc_python_out=. ./protos/users.proto

syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.server.users";
option java_outer_classname = "UsersProto";
option objc_class_prefix = "USRS";

package users;

// The greeting service definition.
service Users {
  rpc LoginUser(LoginUserRequest) returns (AuthUserReponse) {}
  rpc GetUserById(GetUserRequest) returns (User) {}
  rpc GetUsers(GetUsersRequest) returns (GetUsersResponse) {}
  rpc CreateUser(CreateUserRequest) returns (AuthUserReponse) {}
  rpc UpdateUser(UpdateUserRequest) returns (UpdateUserResponse) {}
  rpc DeleteUser(DeIeteUserRequest) returns (DeleteUserResponse) {}
}

message User {
  string id = 1;
  string name = 2;
  string email = 3;
}

message LoginUserRequest {
  string email = 1;
  string password = 2;
}

message CreateUserRequest {
  string name = 1;
  string email = 2;
  string password = 3;
}

message AuthUserReponse {
  User user = 1;
  string token = 2;
}

message GetUsersRequest {}

message GetUsersResponse {
  repeated User users = 1;
}

message GetUserRequest {}

message UpdateUserRequest {
  User user = 1;
}

message UpdateUserResponse {
  User user = 1;
}

message DeIeteUserRequest {
  string id = 1;
}

message DeleteUserResponse {
  User user = 1;
}
